# Generated by Django 5.2.17 on 2026-09-16 09:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('statement_ending_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cleared_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banking.bankaccount')),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_transactions', to='banking.bankaccount')),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_txs', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
